version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "export NODE_ENV=development; npm install; gulp"
    ports:
      - "80:80"
    volumes:
      - ./:/src/:rw
